### PR TITLE
Custom Firefox.exe path option

### PR DESCRIPTION
**Pull request by irvinzz**

### CODE REVIEW

**Comment by irvinzz** [comment]
I signed it!

**Comment by irvinzz** [comment]
I signed it!

**Comment by amarshall** [comment]
For those looking for this feature, know that you may also specify a custom path via the `FIREFOX_BIN` environment variable.

**Comment by irvinzz** [comment]
But `FIREFOX_BIN` variable can't help if i need to use different versions of firefox in same time.
Usage example:
```
customLaunchers: {
            Firefox42: {
                base: "Firefox",
                binPath: env.FIREFOX42BIN || "firefox42"
            },
            Firefox52: {
                base: "Firefox",
                binPath: env.FIREFOX52BIN || "firefox52"
            }
}
```
`karma start karma.conf.js --reporters=progress --browsers=Firefox,Firefox52,Firefox42`

**Comment by birtles** [comment]
I believe this is already covered by the `command` attribute introduced in c53efcc5f0abf72c0213f826d2b147d01241a39c and [documented here](https://github.com/karma-runner/karma-firefox-launcher#custom-firefox-location).

Closing this now but please let me know if I've misunderstood!

**Pull request closed without merging**
