### PR TITLE
feat: support Firefox headless

### PR DESCRIPTION
**Pull request by keithamus**
Closes https://github.com/karma-runner/karma-firefox-launcher/issues/76

### CODE REVIEW

**Comment by keithamus** [comment]
I signed it!

**Comment by abraham** [comment]
This would be great to get in.

**Comment by dpogue** [comment]
This seems to fail on macOS with an error trying to get the DEFAULT_CMD for `FirefoxDeveloperHeadless`. I wonder if it's failing to inherit that from `FirefoxDeveloper` properly.

```
04 10 2017 11:23:25.519:INFO [launcher]: Launching browser FirefoxDeveloperHeadless with unlimited concurrency
04 10 2017 11:23:25.525:INFO [launcher]: Starting browser undefined
04 10 2017 11:23:25.526:ERROR [karma]: TypeError: Cannot read property 'darwin' of undefined
    at Object.ProcessLauncher._getCommand (Project/node_modules/karma/lib/launchers/process.js:37:57)
    at Object.FirefoxBrowser._start (Project/node_modules/karma-firefox-launcher/index.js:112:24)
    at Object.<anonymous> (Project/node_modules/karma/lib/launchers/process.js:19:10)
    at emitOne (events.js:120:20)
    at Object.emit (events.js:210:7)
    at Object.BaseLauncher.start (Project/node_modules/karma/lib/launchers/base.js:42:10)
    at Object.j (Project/node_modules/karma/lib/launcher.js:116:17)
    at Object.setTimeout.bind.j (Project/node_modules/qjobs/qjobs.js:143:18)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
```

**Comment by keithamus** [comment]
@dpogue the latest commit should fix that.

**Comment by dpogue** [comment]
@keithamus Thanks, but I'm still getting errors, now when it's trying to call `_execCommand` from the parent prototype.

```
TypeError: Cannot read property 'call' of undefined
    at Object.value (Project/node_modules/karma-firefox-launcher/index.js:183:58)
    at Object.FirefoxBrowser._start (Project/node_modules/karma-firefox-launcher/index.js:128:10)
    at Object.<anonymous> (Project/node_modules/karma/lib/launchers/process.js:19:10)
    at emitOne (events.js:120:20)
```

**Comment by keithamus** [comment]
Okay; okay. I actually properly did this now. This one definitely works, and is tested.

**Comment by dpogue** [comment]
Just tested it and it's all working now (well, aside from my test failures, but I can't blame you for those). Thanks! :)

**Comment by keithamus** [comment]
Yeah sorry @dpogue I'm really only here to fix this PR 😆. Have you tried turning them off and on again 😜?

**Comment by keithamus** [comment]
CI is failing right now because the CI setup includes the command `npm install -g npm` - but npm@5 dropped Node 0.12 and 0.10. I'd recommend this package drops support for those versions as well, as there are active security vulns for those versions that wont be patched.

**Comment by edmorley** [comment]
#78 has been opened for resolving the unrelated Node 0.10 and 0.12 test failures.

Since the rest of the tests pass, can this be merged? :-)

**Comment by dignifiedquire** [comment]
Thanks:octocat:

**Pull request merged**
