### PR TITLE
Add the "Release" GitHub Actions workflow

### PR DESCRIPTION
**Pull request by jginsburgn**

### CODE REVIEW

**Review by birtles — COMMENTED** [review]
Looks good to me.

My only suggestions are:

* It would be good not to trigger a release unless the tests pass. We can do that either by putting the two tasks in the one file with a suitable `needs:` clause and an `if:` check that this is a push, not a pull_request, but it might be better still to use the [`workflow_run` approach](https://docs.github.com/en/actions/learn-github-actions/events-that-trigger-workflows#workflow_run) since that would allow keeping the files separate.
* I don't think we need `package-lock.json` since we have `yarn.lock`?

**Comment by jginsburgn** [comment]
> It would be good not to trigger a release unless the tests pass. We can do that either by putting the two tasks in the one file with a suitable needs: clause and an if: check that this is a push, not a pull_request, but it might be better still to use the workflow_run approach since that would allow keeping the files separate.

I have made the checks under the `ci.yml` file needed prior to merging a request, so it should be impossible to trigger a release unless all tests pass.

> I don't think we need package-lock.json since we have yarn.lock?

I am removing it then.

**Comment by birtles** [comment]
> I have made the checks under the `ci.yml` file needed prior to merging a request, so it should be impossible to trigger a release unless all tests pass.

Ok, great. I will make sure to submit changes as pull requests in future.

Thank you!

**Review by birtles — APPROVED** [review]

**Comment by jginsburgn** [comment]
Thanks to you! You are a great contributor :) And also please excuse me that I got delayed in addressing this.

**Comment by birtles** [comment]
By the way, it looks like I am not authorized to merge this pull request. I hope I can still continue to maintain this project, unless someone else is prepared to do it instead.

**Comment by jginsburgn** [comment]
Yes! That was unintended. I have been moving some settings around. I think I have fixed that. Can you verify ?

**Pull request merged**
