### PR TITLE
Bypass WSL check if Firefox is present in WSL environment

### PR DESCRIPTION
**Pull request by tstackhouse**
Potential fix for #107

### CODE REVIEW

**Comment by tstackhouse** [comment]
@googlebot I signed it!

**Comment by birtles** [comment]
Merged as 23a5d10baeba016d4c30a7378a795de4561f1160.

Thank you!

**Comment by kyubisation** [comment]
Is this going to be released? I am also running into this problem.

**Comment by birtles** [comment]
> Is this going to be released? I am also running into this problem.

Sorry, I don't have the privileges needed to release a new version but I (finally) filed #121 to release this.

**Pull request closed without merging**
