### PR TITLE
 fix: Detect and kill browser process when launcher process is being used

### LINKED ISSUE #101: Launcher doesn't kill Firefox 68
Firefox : v68.0.1
OS : Window7 and Windows 10
Karma : v1.7.1 || v3.1.4 || 4.2.0
Firefox launcher : v1.1.0
Node.js : v8 || v10

Launcher doesn't kill my Firefox 68, I tested with several version of nodejs
without success.
Maybe it's cause of Electrolyse (e10s) maybe not.
I tried to disable e10s for a moment with set MOZ_FORCE_DISABLE_E10S variable but unsuccessful, I created a little standalone
code to test. 
```js
const spawn = require('child_process').spawn;
let firefox = spawn("pathToFirefox\\firefox.exe, [
    "http://localhost:9876/?id=anid",
    "-profile",
    "C:\\temp\karma-2456",
    "-no-remote",
    "-wait-for-browser"
]);
setTimeout(function killFirefox(){
    firefox.kill();
}, 10000)
firefox.on('exit', function(code, signal){
    console.log('Firefox exit');
});
```
Result: firefox is always running.

I tried with this version [How to kill child processes that spawn their own child processes in Node.js](https://azimi.me/2014/12/31/kill-child_process-node-js.html) but it doesn't work for me.

has anybody an idea ?

### PR DESCRIPTION
**Pull request by birtles**
Fixes #101.

### CODE REVIEW

**Comment by BrennanConroy** [comment]
I'm unable to use this package after this change.
I'm getting: `TypeError: this.on is not a function`

**Comment by birtles** [comment]
Oh, I'm not sure what's going on there. I don't recall how this all fits together, but I _thought_ it should define the `on` method [here](https://github.com/karma-runner/karma/blob/80febfb53a7d041bdcbcffef617e53cdc2d8dd66/lib/launchers/base.js#L24-L26) and it worked for me previously.

I'd like to understand what changed or what is going wrong. I don't suppose you're using a more recent version of karma than 4.2.0, for example?

**Comment by BrennanConroy** [comment]
I'm using karma 3.1.4 and tried 4.4.1, both had the same issue.

**Comment by BrennanConroy** [comment]
`this.on` is valid inside the `_start` function, but not valid outside of that function. No idea why, but would it be possible to modify this and release a new version?

**Comment by johnjbarton** [comment]
@BrennanConroy  Please open an issue with steps to reproduce your problem.

**Comment by BrennanConroy** [comment]
Figured it out. We have some code to check if the browser exists before putting it in the karma config, and instead of using `FirefoxHeadlessBrowser.prototype` we were creating an instance and passing an empty function for the base launcher. Sorry for the false alarm 😄

**Pull request merged**
